maintitle: This is a Jekyll test page
description: |
     <p>Copy text goes here.  It can be on a single line or, it can go over mutliple lines.</p>
      <p>Since we're rendering this out as text you need to use the &lt;/p&gt; syntax to specify paragraphs</p>

sections:
     - pretravel
     - travel
     - transportation
     - city